# Generated by Django 5.2.1 on 2025-05-28 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='geeхам',
            name='participants',
            field=models.ManyToManyField(related_name='exams', to='myapp.user', verbose_name='Пользователи'),
        ),
    ]
